<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CalciService"
     targetNamespace="http://xmlns:srini.org/soa/wsdl/Calci/V1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://xmlns:Srini.org/soa/xsd/Calci"
     xmlns:tns="http://xmlns:srini.org/soa/wsdl/Calci/V1"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns:Srini.org/soa/xsd/Calci" schemaLocation="xsd/Calci.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="payload" element="inp1:CalciReqDetails"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="payload" element="inp1:CalciRespDetails"/>
    </wsdl:message>
    <wsdl:portType name="CalciInterface">
        <wsdl:operation name="procesAdd">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
