<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CalciService"
     targetNamespace="http://xmlns:srini.org/soa/wsdl/Calci/V1"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns:srini.org/soa/wsdl/Calci/V1"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="CalciService">
        <plnk:role name="CalciInterface">
            <plnk:portType name="tns:CalciInterface"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns:srini.org/soa/wsdl/Calci/V1" location="CalciService.wsdl"/>
</wsdl:definitions>
